name: 'Configure vcpkg with NuGet Cache'
description: 'Bootstraps vcpkg and configures NuGet for binary caching'
inputs:
  github_token:
    description: 'GitHub Token for NuGet authentication'
    required: true
  arch:
    description: "Architecture to build for"
    required: true
runs:
  using: "composite"
  steps:
    - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756
      with:
        arch: ${{ inputs.arch }}
    - name: Bootstrap vcpkg
      shell: pwsh
      run: ./third-party/vcpkg/bootstrap-vcpkg.bat
    - name: Configure vcpkg nuget cache
      shell: pwsh
      run: |
        $nuget_exe = (./third-party/vcpkg/vcpkg fetch nuget)
        $nuget_feed_url = "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        "VCPKG_BINARY_SOURCES=clear;nuget,$nuget_feed_url,readwrite" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        
        & $nuget_exe sources add `
          -Source "$nuget_feed_url" `
          -StorePasswordInClearText `
          -Name GitHubPackages `
          -UserName "${{ github.repository_owner }}" `
          -Password "${{ inputs.github_token }}"
        & $nuget_exe setapikey "${{ inputs.github_token }}" `
          -Source "$nuget_feed_url"
